### ISSUE TITLE
JAK.Tooltip - chyba při scrolavání elementu

### ISSUE THREAD

**Issue by alda78** [seznam/JAK#136]
Pokud je element, na kterém je implementován tooltip, součástí divu na kterém se zobrazil vertikální scrollbar, tak se při odscrollování divu níže začne tooltip zobrazovat níž a níž, až se může dostat úplně mimo obrazovku. Asi to bude způsobeno vypočítáváním pozice myši relativně a ne absolutně vůči poloze elementu na obrazovce.

**Comment by ondras** [comment]
Zkuste to prosím s aktuální verzí tooltipu: https://github.com/seznam/JAK/blob/master/widgets/tooltip/tooltip.js

Pokud se situace po této opravě nezlepší, poprosím o konkrétní ukázku stránky/kódu, kde se chyba projevuje.

**Comment by alda78** [comment]
Zdá se že už to funguje lépe, i když se změnil jenom jeden řádek kódu oproti tomu co jsme používali. Díky.

**Comment by ondras** [comment]
:-)
