### ISSUE TITLE
Add childIndex property

### ISSUE THREAD

**Issue by eorroe** [seznam/JAK#137]
The `childIndex` property would return the index of that child Element from parent

```JS
Object.defineProperty(Node.prototype, 'childIndex', {
	get() {
		var currentElement = this.parentElement.firstElementChild, index = 0;
		while(currentElement.nextElementSibling) {
			if(this == currentElement) {
				return index;
			} else {
				index++;
				currentElement = currentElement.nextElementSibling;
			}
		}
	}
});
```

**Comment by ondras** [comment]
Is this a standardized API? Can you point me to some official docs for this?

**Comment by eorroe** [comment]
No it's not, it's an idea.

**Comment by ondras** [comment]
Ah. Well, even if the idea is useful (it is, in this particular case), we try to modify native prototypes only by adding standardized APIs (polyfills) to avoid potential namespace clashes and forward compatibility issues.

**Comment by eorroe** [comment]
Oh I saw this reference from mdn, which is under development I believe so I thought why not suggest the idea here, instead of in specifiction.org.
